apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: efs-static #We should provide the Pv name
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels: 
    purpose: efs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: efs-static
      mountPath: /data
  volumes:
  - name: efs-static
    persistentVolumeClaim:
      claimName: efs-static
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007